<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\ak\AvatarPreviewInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\user\UserInterface;

/**
 * ID of a `picture` field attached to a user entity.
 *
 * The field is the target for the active avatar preference for the user.
 */
const AK_FIELD_PICTURE_ACTIVE = 'user_picture';

/**
 * ID of a `picture` field attached to a user entity.
 *
 * The field has a reference to the last picture the user manually updated.
 */
const AK_FIELD_PICTURE_USER = 'ak_user_picture';

/**
 * ID of a `list_string` field attached to a user entity.
 *
 * The field contains the user avatar generator preference.
 */
const AK_FIELD_AVATAR_GENERATOR = 'ak_avatar_generator';

/**
 * Implements hook_cron().
 */
function ak_cron() {
  $intervals = \Drupal::config('ak.settings')->get('refresh_interval');
  $ak_preview_storage = \Drupal::entityManager()->getStorage('ak_preview');
  /** @var \Drupal\ak\AvatarGeneratorPluginManagerInterface $avatar_generators $avatar_generator */
  $avatar_generators = \Drupal::service('plugin.manager.avatar_generator');

  // Remove expired previews.
  foreach ($avatar_generators->getDefinitions() as $avatar_generator => $definition) {
    $query = $ak_preview_storage
      ->getQuery()
      ->condition('avatar_generator', $avatar_generator);

    if ($definition['dynamic']) {
      $offset = $intervals['dynamic'] > 0 ? $intervals['dynamic'] : 0;
      $query->condition('created', REQUEST_TIME - $offset, '<');
    }
    else {
      $offset = $intervals['static'] > 0 ? $intervals['static'] : 0;
      if ($offset) {
        $query->condition('created', REQUEST_TIME - $offset, '<');
        $query->condition('scope', AvatarPreviewInterface::SCOPE_TEMPORARY, '=');
      }
      else {
        continue;
      }
    }

    $ids = $query->execute();
    $ak_preview_storage->delete($ak_preview_storage->loadMultiple($ids));
  }
}

/**
 * Implements hook_entity_field_access().
 */
function ak_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  /** @var \Drupal\ak\AvatarManager $avatar_manager */
  $avatar_manager = \Drupal::service('ak.avatar_manager');
  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  if ($field_definition->getName() == AK_FIELD_PICTURE_ACTIVE && $operation == 'view' && $field_definition->getTargetEntityTypeId() == 'user') {
    if ($items) {
      $user = $items->getEntity();
      $avatar_manager->syncAvatar($user);
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_presave().
 */
function ak_entity_presave(EntityInterface $entity) {
  if ($entity instanceof UserInterface) {
    /** @var \Drupal\ak\AvatarManager $avatar_manager */
    $avatar_manager = \Drupal::service('ak.avatar_manager');
    $avatar_manager->invalidateUserAvatar($entity);
    // @todo: only notify if value of AK_FIELD_PICTURE_USER changed
    $avatar_manager->notifyDynamicChange('user', $entity);
  }
}

/**
 * To be consumed by field AK_FIELD_AVATAR_GENERATOR allowed_values_function.
 *
 * Implements callback_allowed_values_function().
 *
 * @return string[int]
 */
function ak_callback_avatar_generators(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  /** @var \Drupal\ak\AvatarGeneratorPluginManagerInterface $avatar_generators $avatar_generator */
  $avatar_generators = \Drupal::service('plugin.manager.avatar_generator');

  $options = [];
  foreach ($avatar_generators->getDefinitions() as $plugin_id => $definition) {
    if ($plugin_id != 'broken') {
      if ($entity instanceof UserInterface && $entity->hasPermission("ak avatar_generator user $plugin_id")) {
        $options[$plugin_id] = $definition['label'];
      }
    }
  }

  return $options;
}